# Generated by Django 3.0.5 on 2021-05-26 16:54

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210526_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT')], default='savings', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default=Users.models.User.get_account_number, editable=False, max_length=14, unique=True),
        ),
    ]
