# Generated by Django 3.0.5 on 2021-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210526_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'SAVINGS'), ('Current', 'CURRENT')], default='SAVINGS', max_length=10),
        ),
    ]
