# Generated by Django 3.1.6 on 2021-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='m', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('TV', 'TV'), ('XCHANGE', 'XCHANGE'), ('IDEAL', 'IDEAL')], max_length=20),
        ),
    ]
