# Generated by Django 3.1.6 on 2021-02-06 17:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210206_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.FileField(default='l', upload_to=core.models.Blog.get_path),
            preserve_default=False,
        ),
    ]
