# Generated by Django 3.0.5 on 2021-05-08 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True)),
                ('activation_cost', models.FloatField()),
                ('duration', models.PositiveIntegerField()),
                ('interest', models.FloatField()),
                ('interest_rate', models.FloatField(blank=True)),
            ],
            options={
                'ordering': ['-activation_cost'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('coin', models.CharField(choices=[('BTC', 'BTC'), ('USDT', 'USDT'), ('ETH', 'ETH'), ('BNB', 'BNB')], max_length=10)),
                ('wallet_address', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], max_length=20)),
                ('amount_paid', models.FloatField()),
                ('is_received', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_withdrawal_ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start', models.DateTimeField(null=True)),
                ('plan_end', models.DateTimeField(null=True)),
                ('initial_balance', models.FloatField(default=0.0)),
                ('set_amount', models.FloatField(blank=True, null=True)),
                ('expected_maximum_balance', models.FloatField(default=0.0)),
                ('plan_is_active', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_plan', to='wallet.Plan')),
                ('preferred_currency', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='preferred_currency', to='wallet.Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL', 'WITHDRAWAL'), ('DEPOSIT', 'DEPOSIT')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('coin', models.CharField(choices=[('BTC', 'BTC'), ('USDT', 'USDT'), ('ETH', 'ETH'), ('BNB', 'BNB')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('coin', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_deposits', to='wallet.Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_pending_deposit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
