# Generated by Django 3.0.5 on 2021-05-20 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_pin', models.CharField(max_length=6)),
                ('iban_number', models.CharField(max_length=30)),
                ('otp', models.CharField(max_length=8)),
                ('balance', models.FloatField(default=0.0)),
                ('available_balance', models.FloatField()),
                ('allowed_to_transact', models.BooleanField(default=True)),
                ('disallow_reason', models.TextField()),
                ('is_frozen', models.BooleanField(default=False)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='wallet.AccountType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('debit', 'DEBIT'), ('credit', 'CREDIT')], max_length=10)),
                ('nature', models.CharField(choices=[('withdrawal', 'WITHDRAWAL'), ('deposit', 'DEPOSIT'), ('transfer', 'TRANSFER')], max_length=12)),
                ('status', models.CharField(choices=[('failed', 'FAILED'), ('processing', 'PROCESSING'), ('successful', 'SUCCESSFUL')], max_length=10)),
                ('description', models.TextField()),
                ('status_message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receiver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
