# Generated by Django 3.0.5 on 2021-05-26 16:39

from django.db import migrations, models
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=20),
        ),
    ]
