# Generated by Django 3.0.5 on 2021-05-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20210526_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='disallow_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_pin',
            field=models.CharField(default='0000', max_length=6),
        ),
    ]
