# Generated by Django 3.0.5 on 2021-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20210526_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
