# Generated by Django 3.0.5 on 2021-05-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20210528_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Internal Transfer ', 'Internal Transfer'), ('Domestic Transfer', 'Domestic Transfer'), ('International Transfer', 'International Transfer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10),
        ),
    ]
