# Generated by Django 3.0.5 on 2021-05-30 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0009_auto_20210528_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='iban',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='swift_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nature',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Internal Transfer', 'Internal Transfer'), ('Domestic Transfer', 'Domestic Transfer'), ('International Transfer', 'International Transfer')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Processing', 'Processing'), ('Successful', 'Successful')], max_length=10),
        ),
    ]
