# Generated by Django 3.0.5 on 2021-05-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20210530_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bic',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
