# Generated by Django 3.0.5 on 2021-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_transaction_bic'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
