# Generated by Django 3.0.5 on 2021-06-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20210530_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
